# Generated by Django 5.2.4 on 2025-07-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',), 'verbose_name': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at',), 'verbose_name': 'Рецепт'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-created_at',), 'verbose_name': 'Корзина'},
        ),
    ]
